### ISSUE TITLE
No code yet?

### ISSUE THREAD

**Issue by chancesmith** [codeschool/ShapingUpWithAngular.js#2]
Please add code :)

**Comment by bijanbwb** [comment]
This might help:

http://codeschool.reamaze.com/kb/course-issues/is-there-a-demo-app-with-source-code-for-the-angular-course

**Comment by adamfortuna** [comment]
@alyssamichelle - Think you could copy of the code over to GitHub sometime? No rush on this as it's available on Plunker now, but even a readme linking to the Plunker would probably help out. :)

**Comment by alyssamichelle** [comment]
http://cl.nicoll.co/Za6I

**Comment by adamfortuna** [comment]
Looks like we'll need to move over the code in the private repo to this public one.

**Comment by alyssamichelle** [comment]
Done! and with a README :D
